[connection]
id=Work VPN
uuid=10c5ea72-986e-4e67-a09d-85c55b8a7a20
type=vpn
autoconnect=false

[vpn]
gateway=46.146.203.234
user-auth-type=password
user=inaidanov@neoplatform.ru
machine-auth-type=psk
ipsec-enabled=true
service-type=org.freedesktop.NetworkManager.l2tp

[ipv4]
method=auto
ignore-auto-routes=false
ignore-auto-dns=false
dhcp-send-hostname=true
never-default=false
